FROM golang:1.25-alpine AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go test -c ./integration/ -o /integration.test

FROM alpine:3.19

COPY --from=builder /integration.test /integration.test

ENV PROXY_ADDR=proxy:5555
ENV WAIT_FOR_PROXY=60

ENTRYPOINT ["/integration.test"]
CMD ["-test.v", "-test.timeout=120s"]
